name: dirs
description: Dir viewer

dependencies:
    browser: any
    polymer: any
    core_elements: any
    paper_elements: any
    logging: any
    quiver: any

transformers:
- polymer:
    entry_points: web/index.html
